name: wonderkids.math
description: WonderKids Vui Học Toán
publish_to: "none" # chỉ dùng nội bộ

version: 1.0.0+3

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_tts: ^3.8.5
  audioplayers: ^6.5.1
  provider: ^6.1.5+1
  flip_card: ^0.7.0
  confetti: ^0.8.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  lottie: ^3.1.0
  google_mobile_ads: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.3
  google_sign_in: ^6.2.0
  firebase_analytics: ^12.0.3
  firebase_storage: ^13.0.2
  firebase_app_check: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_padding: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/mascot/
    - assets/images/numbers/
    - assets/images/balloon1.png
    - assets/images/balloon2.png
    - assets/images/balloon3.png
    - assets/images/icon_apple.png
    - assets/images/icon_tree.png
    - assets/images/icon_bridge.png
    - assets/images/icon_cave.png
    - assets/images/icon_scale.png
    - assets/images/icon_river.png
    - assets/images/icon_desert.png
    - assets/images/icon_city.png
    - assets/images/icon_clock.png
    - assets/images/icon_castle.png
    - assets/images/icon_start.png
    - assets/images/icon_end.png

    - assets/audios/
    - assets/audios/numbers/

    - assets/configs/
    - assets/configs/numbers.json
    - assets/configs/numbers_20.json
